version: '2'
services:
  racingcompanyweb-app:
    image: racingcompanyweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://racingcompanyweb-postgresql:5432/racingCompanyWeb
      - JHIPSTER_CACHE_MEMCACHED_SERVERS=racingcompanyweb-memcached:11211
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://racingcompanyweb-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://racingcompanyweb-elasticsearch:9200
    ports:
      - 8080:8080
  racingcompanyweb-postgresql:
    extends:
      file: postgresql.yml
      service: racingcompanyweb-postgresql
  racingcompanyweb-memcached:
    extends:
      file: memcached.yml
      service: racingcompanyweb-memcached
  racingcompanyweb-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: racingcompanyweb-elasticsearch
