version: '2'
services:
  mudflaptruckstopweb-app:
    image: mudflaptruckstopweb
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mudflaptruckstopweb-postgresql:5432/mudflapTruckstopWeb
      - JHIPSTER_CACHE_MEMCACHED_SERVERS=mudflaptruckstopweb-memcached:11211
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mudflaptruckstopweb-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mudflaptruckstopweb-elasticsearch:9200
    ports:
      - 8080:8080
  mudflaptruckstopweb-postgresql:
    extends:
      file: postgresql.yml
      service: mudflaptruckstopweb-postgresql
  mudflaptruckstopweb-memcached:
    extends:
      file: memcached.yml
      service: mudflaptruckstopweb-memcached
  mudflaptruckstopweb-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mudflaptruckstopweb-elasticsearch
